### ISSUE TITLE
weird WiFiManager in use instead of WifiManager

### ISSUE THREAD

**Issue by ulno** [sekassel/CoronaTrackerEsp32#33]
It is very hard to make this project compile under Linux as there is some weirdness going on with the WiFiManager in use (usualy systems use WifiManager). As Windows doesn't care about capitalization in Filenames - there might be no problems there.
I think in the future ESP32WifiManager should be used to prevent this confusion.

**Comment by YannickNagel** [comment]
Hello.
To make sure I understand correctly: 
`WifiManager.h` would work but `WiFiManager.h` does not? If so, this is indeed rather weird. Maybe you have installed multiple Wifimanagers (globally) in PlatformIO which now conflict with the one we use?

Could you link the mentioned *ESP32WifiManager* because the one I [found](https://github.com/madhephaestus/Esp32WifiManager) does not do the same things as our current WiFiManager.

You might also consider to post this issue to the original [library repository](https://github.com/tzapu/WiFiManager) if the problem is indeed the with the library itself.

**Comment by ulno** [comment]
I see in platformio.ini the following: https://github.com/tzapu/WiFiManager.git#development

When I search the platformio-libraries for wifimanager I get :
- WifiManger by tzapu (https://github.com/tzapu) that seems to use WiFiManager.h but seems to support only the esp8266 - so I am wondering about your #development flag
- ESP_WiFiManager by Khoi Hoang which seems to support also ESP32 always using the3 WiFi spelling
- and ESP32WifiManager by Kevin Harrington (https://github.com/madhephaestus/Esp32WifiManager) that uses the Wifi spelling

So I am just wondering, why we use here tzapu's development version.

**Comment by YannickNagel** [comment]
- The flag comes from PlatformIO's naming scheme for including [git librarys](https://docs.platformio.org/en/latest/core/userguide/lib/cmd_install.html#git). The correct link would be [https://github.com/tzapu/WiFiManager/tree/development](https://github.com/tzapu/WiFiManager/tree/development). We use the development branch because it supports ESP32.
- This library could also be used for configuration. Although the examples are more complicated it seems to work similarly.
- This manager does not open a web portal to configure credentials and cannot replace the current approach for configuration.

As to why tzapu's version is used: It was probably the first library I found and got to work correctly.
